//
//  ShopDetailRouter.swift
//  FoodLogger
//
//  Created by Takahiro Kato on 2017/09/24.
//  Copyright © 2017年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ShopDetailRoutingLogic {
    func routeToCreateShopMemo(segue: UIStoryboardSegue?)
}

protocol ShopDetailDataPassing {
    var dataStore: ShopDetailDataStore? { get }
}

class ShopDetailRouter: NSObject, ShopDetailRoutingLogic, ShopDetailDataPassing {
    weak var viewController: ShopDetailViewController?
    var dataStore: ShopDetailDataStore?
    
    // MARK: Routing
    
    func routeToCreateShopMemo(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! CreateShopMemoViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToCreateShopMemo(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "CreateShopMemoViewController") as! CreateShopMemoViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToCreateShopMemo(source: dataStore!, destination: &destinationDS)
            navigateToCreateShopMemo(source: viewController!, destination: destinationVC)
        }
    }

    // MARK: Navigation
  
    func navigateToCreateShopMemo(source: ShopDetailViewController, destination: CreateShopMemoViewController) {
        source.show(destination, sender: nil)
    }

    // MARK: Passing data
  
    func passDataToCreateShopMemo(source: ShopDetailDataStore, destination: inout CreateShopMemoDataStore) {
        destination.shop = source.shop
        destination.location = source.location
    }
}
