//
//  ShopDetailInteractor.swift
//  FoodLogger
//
//  Created by Takahiro Kato on 2017/09/24.
//  Copyright © 2017年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreLocation

protocol ShopDetailBusinessLogic {
    func fetchShopInfo(request: ShopDetail.FetchShopInfo.Request)
    func fetchShopStatus(request: ShopDetail.FetchShopStatus.Request)
}

protocol ShopDetailDataStore {
    var shop: HotpepperShop! { get set }
    var location: CLLocation! { get set }
}

class ShopDetailInteractor: ShopDetailBusinessLogic, ShopDetailDataStore {
    var presenter: ShopDetailPresentationLogic?
    var worker = ShopsWorker(dataStore: RealmShopManager.sharedInstance)
    var shop: HotpepperShop!
    var location: CLLocation!
    
    // MARK: Fetch shop information
  
    func fetchShopInfo(request: ShopDetail.FetchShopInfo.Request) {
        let response = ShopDetail.FetchShopInfo.Response(shop: shop)
        presenter?.presentShopInfo(response: response)
    }
    
    // MARK: Fetch shop status
    func fetchShopStatus(request: ShopDetail.FetchShopStatus.Request) {
        worker.fetchShop(id: shop.id ?? "0") { (shop) in
            let response = ShopDetail.FetchShopStatus.Response(shop: shop)
            self.presenter?.presentShopStatus(response: response)
        }
    }
}
