//
//  ShopDetailPresenter.swift
//  FoodLogger
//
//  Created by Takahiro Kato on 2017/09/24.
//  Copyright © 2017年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShopDetailPresentationLogic {
    func presentShopInfo(response: ShopDetail.FetchShopInfo.Response)
    func presentShopStatus(response: ShopDetail.FetchShopStatus.Response)
}

class ShopDetailPresenter: ShopDetailPresentationLogic {
    weak var viewController: ShopDetailDisplayLogic?
  
    // MARK: Present shop information
  
    func presentShopInfo(response: ShopDetail.FetchShopInfo.Response) {
        var resultURL: URL!
        if let shopURL = response.shop.shopURL, let url = URL(string: shopURL) {
            resultURL = url
        }
        let viewModel = ShopDetail.FetchShopInfo.ViewModel(shopURL: resultURL)
        viewController?.displayShopInfo(viewModel: viewModel)
    }
    
    // MARK: Present shop status
    func presentShopStatus(response: ShopDetail.FetchShopStatus.Response) {
        var result: Bool = false
        if response.shop != nil {
            result = true
        }
        let viewModel = ShopDetail.FetchShopStatus.ViewModel(isSaved: result)
        viewController?.displayShopStatus(viewModel: viewModel)
    }
}
