//
//  ShopDetailModels.swift
//  FoodLogger
//
//  Created by Takahiro Kato on 2017/09/24.
//  Copyright © 2017年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ShopDetail {
    
    // MARK: Fetch shop information
    enum FetchShopInfo {
        struct Request {
        }
        struct Response {
            var shop: HotpepperShop
        }
        struct ViewModel {
            var shopURL: URL
        }
    }
    
    // MARK: Fetch shop status
    enum FetchShopStatus {
        struct Request {
        }
        struct Response {
            var shop: HotpepperShop?
        }
        struct ViewModel {
            var isSaved: Bool
        }
    }
}
