//
//  ShopDetailViewController.swift
//  FoodLogger
//
//  Created by Takahiro Kato on 2017/07/23.
//  Copyright © 2017年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import UIKit
import CoreLocation
import NVActivityIndicatorView

protocol ShopDetailDisplayLogic: class {
    func displayShopInfo(viewModel: ShopDetail.FetchShopInfo.ViewModel)
    func displayShopStatus(viewModel: ShopDetail.FetchShopStatus.ViewModel)
}

class ShopDetailViewController: UIViewController, ShopDetailDisplayLogic {
    var interactor: ShopDetailBusinessLogic?
    var router: (NSObjectProtocol & ShopDetailRoutingLogic & ShopDetailDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = ShopDetailInteractor()
        let presenter = ShopDetailPresenter()
        let router = ShopDetailRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        configureWebView()
        fetchShopInfoOnLoad()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        fetchShopStatus()
    }
    
    // MARK: Fetch shop information
    
    /// WebView
    @IBOutlet weak var webView: UIWebView!
    /// ショップ保存ボタン
    @IBOutlet weak var saveButton: UIBarButtonItem!
    /// ローディングビュー
    @IBOutlet weak var loadingView: UIView!
    /// ローディングアイコン
    @IBOutlet weak var indicatorView: NVActivityIndicatorView!
    
    func configureWebView() {
        webView.delegate = self
        self.indicatorView.startAnimating()
    }
    
    func fetchShopInfoOnLoad() {
        let request = ShopDetail.FetchShopInfo.Request()
        interactor?.fetchShopInfo(request: request)
    }
    
    func displayShopInfo(viewModel: ShopDetail.FetchShopInfo.ViewModel) {
        let urlRequest = URLRequest(url: viewModel.shopURL)
        webView.loadRequest(urlRequest)
    }
    
    // MARK: Fetch shop status
    
    func fetchShopStatus() {
        let request = ShopDetail.FetchShopStatus.Request()
        interactor?.fetchShopStatus(request: request)
    }
    
    func displayShopStatus(viewModel: ShopDetail.FetchShopStatus.ViewModel) {
        let isSaved = viewModel.isSaved
        if isSaved {
            saveButton.isEnabled = false
        }
    }
    
    // MARK: Button Action
    @IBAction func touchSaveButton(_ sender: Any) {
        self.performSegue(withIdentifier: "routeToCreateShopMemoSegue", sender: nil)
        router?.routeToCreateShopMemo(segue: nil)
    }
}

extension ShopDetailViewController: UIWebViewDelegate {
    func webViewDidFinishLoad(_ webView: UIWebView) {
        self.indicatorView.stopAnimating()
        
        UIView.animate(withDuration: 2.0) {
            self.loadingView.isHidden = true
        }
    }
}
/*
class ShopDetailViewController: UIViewController, UIWebViewDelegate {
    /// 現在地
    internal var myLocation: CLLocation?
    /// ショップ
    internal var shop: HotpepperShop!
    /// ショップの保存済/未保存フラグ
    internal var isSaved: Bool = false
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    // MARK: Storyboard Segue
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        let backButton = UIBarButtonItem.init()
        backButton.title = "戻る"
        backButton.tintColor = UIColor.white
        self.navigationController?.navigationBar.tintColor = UIColor.white
        self.navigationItem.backBarButtonItem = backButton
        
        if segue.identifier == "createShopMemoSegue" {
            guard let createShopMemoViewController = segue.destination as? CreateShopMemoViewController else {
                return
            }
            createShopMemoViewController.shop = self.shop
            createShopMemoViewController.myLocation = self.myLocation
        }
    }
}
 */
