//
//  ShopListPresenter.swift
//  FoodLogger
//
//  Created by Takahiro Kato on 2017/09/24.
//  Copyright © 2017年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShopListPresentationLogic {
    func presentFetchedMyShops(response: ShopList.FetchMyShop.Response)
    func presentSelectedShop(response: ShopList.SelectShop.Response)
}

class ShopListPresenter: ShopListPresentationLogic {
    weak var viewController: ShopListDisplayLogic?
    
    // MARK: Present my shop
    func presentFetchedMyShops(response: ShopList.FetchMyShop.Response) {
        var displayShops: [MyShop] = []
        if let shops = response.shops {
            displayShops = shops
        }
        let viewModel = ShopList.FetchMyShop.ViewModel(shops: displayShops)
        viewController?.displayMyShop(viewModel: viewModel)
    }
    
    // MARK: Select one shop
    func presentSelectedShop(response: ShopList.SelectShop.Response) {
        viewController?.transitionToCreateShopMemo(viewModel: ShopList.SelectShop.ViewModel())
    }
}
