//
//  ShopListInteractor.swift
//  FoodLogger
//
//  Created by Takahiro Kato on 2017/09/24.
//  Copyright © 2017年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShopListBusinessLogic {
    func fetchMyShop(request: ShopList.FetchMyShop.Request)
    func selectShop(request: ShopList.SelectShop.Request)
}

protocol ShopListDataStore {
    var shop: HotpepperShop! { get set }
}

class ShopListInteractor: ShopListBusinessLogic, ShopListDataStore {
    var presenter: ShopListPresentationLogic?
    var worker = ShopsWorker(dataStore: RealmShopManager.sharedInstance)
    var shop: HotpepperShop!
  
    // MARK: Fetch my shop
    func fetchMyShop(request: ShopList.FetchMyShop.Request) {
        worker.fetchShops { (shops) in
            let response = ShopList.FetchMyShop.Response(shops: shops)
            self.presenter?.presentFetchedMyShops(response: response)
        }
    }
    
    // MARK: Select one shop
    func selectShop(request: ShopList.SelectShop.Request) {
        shop = request.shop
        let response = ShopList.SelectShop.Response()
        self.presenter?.presentSelectedShop(response: response)
    }
}
