//
//  ShopListModel.swift
//  FoodLogger
//
//  Created by Takahiro Kato on 2017/09/24.
//  Copyright © 2017年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ShopList {
    // MARK: Fetch my shop
    
    enum FetchMyShop {
        struct Request {
        }
        struct Response {
            var shops: [MyShop]?
        }
        struct ViewModel {
            var shops: [MyShop]
        }
    }
    
    // MARK: Select one shop
    enum SelectShop {
        struct Request {
            var shop: HotpepperShop
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
}
