//
//  CreateShopMemoModels.swift
//  FoodLogger
//
//  Created by Takahiro Kato on 2017/09/24.
//  Copyright © 2017年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreateShopMemo {
    
    // MARK: Fetch shop status
    enum FetchShopStatus {
        struct Request {
        }
        struct Response {
            var shop: MyShop?
        }
        struct ViewModel {
            struct SavedShop {
                var shop: MyShop?
                var isSaved: Bool
            }
            var savedShop: SavedShop
        }
    }
    
    // MARK: Create my shop
    enum CreateMyShop {
        struct Request {
            var rating: Int
            var memo: String
            var images: [UIImage]
            var mealTime: Int
        }
        struct Response {
            var isSaved: Bool
            var message: String?
        }
        struct ViewModel {
            var isSaved: Bool
            var message: String?
        }
    }
    
    // MARK: Update my shop
    enum UpdateMyShop {
        struct Request {
            var rating: Int
            var memo: String
            var images: [UIImage]
            var mealTime: Int
        }
        struct Response {
            var isSaved: Bool
            var message: String?
        }
        struct ViewModel {
            var isSaved: Bool
            var message: String?
        }
    }
    
    // MARK: Upload image
    enum UploadImage {
        struct Request {
            
        }
        struct Response {
            
        }
        struct ViewModel {
            
        }
    }
}
