//
//  CreateShopMemoPresenter.swift
//  FoodLogger
//
//  Created by Takahiro Kato on 2017/09/24.
//  Copyright © 2017年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateShopMemoPresentationLogic {
    func presentShopStatus(response: CreateShopMemo.FetchShopStatus.Response)
}

class CreateShopMemoPresenter: CreateShopMemoPresentationLogic {
    
    weak var viewController: CreateShopMemoDisplayLogic?
    
    // MARK: Present shop status
    func presentShopStatus(response: CreateShopMemo.FetchShopStatus.Response) {
        var isSaved: Bool = false
        if response.shop != nil {
            isSaved = true
        }
        var displaySavedShop = CreateShopMemo.FetchShopStatus.ViewModel.SavedShop(shop: response.shop, isSaved: isSaved)
        let viewModel = CreateShopMemo.FetchShopStatus.ViewModel(savedShop: displaySavedShop)
        viewController?.displayShopStatus(viewModel: viewModel)
    }
}
