//
//  CreateShopMemoRouter.swift
//  FoodLogger
//
//  Created by Takahiro Kato on 2017/09/24.
//  Copyright © 2017年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CreateShopMemoRoutingLogic {
    func routeToMapView(segue: UIStoryboardSegue?)
}

protocol CreateShopMemoDataPassing {
    var dataStore: CreateShopMemoDataStore? { get }
}

class CreateShopMemoRouter: NSObject, CreateShopMemoRoutingLogic, CreateShopMemoDataPassing {
    weak var viewController: CreateShopMemoViewController?
    var dataStore: CreateShopMemoDataStore?
    
    // MARK: Routing
    
    func routeToMapView(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! MapViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToMapView(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "MapViewController") as! MapViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToMapView(source: dataStore!, destination: &destinationDS)
            navigateToMapView(source: viewController!, destination: destinationVC)
        }
    }

    // MARK: Navigation
    
    func navigateToMapView(source: CreateShopMemoViewController, destination: MapViewController) {
        source.show(destination, sender: nil)
    }

    // MARK: Passing data
    
    func passDataToMapView(source: CreateShopMemoDataStore, destination: inout MapViewDataStore) {
        destination.savedView = true
    }
}
