//
//  MapViewModel.swift
//  FoodLogger
//
//  Created by Takahiro Kato on 2017/09/24.
//  Copyright © 2017年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MapView {
    
    // MARK: Init map view
    enum InitMapView {
        struct Request {
            var latitude: Double
            var longitude: Double
        }
        struct Response {
            var latitude: Double
            var longitude: Double
        }
        struct ViewModel {
            var latitude: Double
            var longitude: Double
            var zoomLevel: Float
        }
    }
    
    // MARK: Saved map view
    enum SavedMapView {
        struct Request {
        }
        struct Response {
            var marker: CustomGMSMarker
            var shop: MyShop
        }
        struct ViewModel {
            var marker: CustomGMSMarker
            var shop: HotpepperShop
            var rating: Int
        }
    }
    
    // MARK: Fetch my shop
    enum FetchMyShop {
        struct Request {
        }
        struct Response {
            var shops: [MyShop]?
        }
        struct ViewModel {
            struct SavedMarker {
                var shop: HotpepperShop
                var rating: Int
                var type: MarkerType
            }
            var savedMarkers: [SavedMarker]
        }
    }
    
    // MARK: Fetch around shop
    enum FetchAroundShop {
        struct Request {
            var latitude: Double
            var longitude: Double
        }
        struct Response {
            var shops: [HotpepperShop]?
            var isError: Bool
            var isFirstSearch: Bool
        }
        struct ViewModel {
            struct SearchedMarker {
                var shop: HotpepperShop
                var type: MarkerType
            }
            var searchedMarkers: [SearchedMarker]?
            var isFirstSearch: Bool
        }
    }
    
    // MARK: Select one shop
    enum SelectShop {
        struct Request {
            var marker: CustomGMSMarker
            var shop: HotpepperShop
            var latitude: Double
            var longitude: Double
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
}
