//
//  MapViewRouter.swift
//  FoodLogger
//
//  Created by Takahiro Kato on 2017/09/24.
//  Copyright © 2017年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MapViewRoutingLogic {
    func routeToShopList(segue: UIStoryboardSegue?)
    func routeToShopDetail(segue: UIStoryboardSegue?)
}

protocol MapViewDataPassing {
    var dataStore: MapViewDataStore? { get }
}

class MapViewRouter: NSObject, MapViewRoutingLogic, MapViewDataPassing {
    weak var viewController: MapViewController?
    var dataStore: MapViewDataStore?
  
    // MARK: Routing
  
    func routeToShopList(segue: UIStoryboardSegue?) {
        if let segue = segue {
          let destinationVC = segue.destination as! ShopListViewController
          var destinationDS = destinationVC.router!.dataStore!
          passDataToShopList(source: dataStore!, destination: &destinationDS)
        } else {
          let storyboard = UIStoryboard(name: "Main", bundle: nil)
          let destinationVC = storyboard.instantiateViewController(withIdentifier: "ShopListViewController") as! ShopListViewController
          var destinationDS = destinationVC.router!.dataStore!
          passDataToShopList(source: dataStore!, destination: &destinationDS)
          navigateToShopList(source: viewController!, destination: destinationVC)
        }
    }
    
    func routeToShopDetail(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! ShopDetailViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShopDetail(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "ShopDetailViewController") as! ShopDetailViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShopDetail(source: dataStore!, destination: &destinationDS)
            navigationToShopDetail(source: viewController!, destination: destinationVC)
        }
    }

    // MARK: Navigation
    
    func navigateToShopList(source: MapViewController, destination: ShopListViewController) {
        source.show(destination, sender: nil)
    }
    
    func navigationToShopDetail(source: MapViewController, destination: ShopDetailViewController) {
        source.show(destination, sender: nil)
    }
  
    // MARK: Passing data
    
    func passDataToShopList(source: MapViewDataStore, destination: inout ShopListDataStore) {
    }
    
    func passDataToShopDetail(source: MapViewDataStore, destination: inout ShopDetailDataStore) {
        destination.shop = source.selectedShop
        destination.location = source.myLocation
    }
}
