//
//  MapViewWorker.swift
//  FoodLogger
//
//  Created by Takahiro Kato on 2017/09/24.
//  Copyright © 2017年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SwiftyJSON

// MARK: MapView Worker
class MapViewWorker {
    let hotpepperApi = HotpepperAPI()
    
    func searchShop(latitude: Double, longitude: Double, success: @escaping (([HotpepperShop]) -> Void), failure: @escaping ((Error) -> Void)) {
        hotpepperApi.searchRestaurant(latitude: latitude, longitude: longitude, success: { (result) in
            var searchShops: [HotpepperShop] = []
            if let shops = result.array {
                for shop in shops {
                    searchShops.append(HotpepperShop(data: shop))
                }
            }
            success(searchShops)
        }) { (error) in
            failure(error)
        }
    }
}
