//
//  MapViewPresenter.swift
//  FoodLogger
//
//  Created by Takahiro Kato on 2017/09/24.
//  Copyright © 2017年 Takahiro Kato. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MapViewPresentationLogic {
    func presentFetchedMyShops(response: MapView.FetchMyShop.Response)
    func presentFetchedAroundShops(response: MapView.FetchAroundShop.Response)
    func presentSelectedShop(response: MapView.SelectShop.Response)
}

class MapViewPresenter: MapViewPresentationLogic {
    weak var viewController: MapViewDisplayLogic?

    // MARK: Present my shop
    func presentFetchedMyShops(response: MapView.FetchMyShop.Response) {
        var displayedShops: [MapView.FetchMyShop.ViewModel.SavedMarker] = []
        if let shops = response.shops {
            for shop in shops {
                let hotpepperShop = shop as HotpepperShop
                let savedMarker = MapView.FetchMyShop.ViewModel.SavedMarker(shop: hotpepperShop, rating: shop.rating, type: MarkerType.saved)
                displayedShops.append(savedMarker)
            }
        }
        let viewModel = MapView.FetchMyShop.ViewModel(savedMarkers: displayedShops)
        viewController?.displayMyShop(viewModel: viewModel)
    }
    
    // MARK: Present around shop
    func presentFetchedAroundShops(response: MapView.FetchAroundShop.Response) {
        var displayedShops: [MapView.FetchAroundShop.ViewModel.SearchedMarker] = []
        if let shops = response.shops {
            for shop in shops {
                let searchedMarker = MapView.FetchAroundShop.ViewModel.SearchedMarker(shop: shop, type: MarkerType.searched)
                displayedShops.append(searchedMarker)
            }
        }
        let viewModel = MapView.FetchAroundShop.ViewModel(searchedMarkers: displayedShops)
        viewController?.displaySearchedShop(viewModel: viewModel)
    }
    
    // MARK: Select one shop
    func presentSelectedShop(response: MapView.SelectShop.Response) {
        viewController?.transitionToShopDetail(viewModel: MapView.SelectShop.ViewModel())
    }
}
